export { default as AuthBg } from './components/AuthBg.vue'
export { default as AuthHeader } from './components/AuthHeader.vue'
export { default as LoginForm } from './components/LoginForm.vue'
export { default as RegisterForm } from './components/RegisterForm.vue'
export { default as EmailAuthForm } from './components/EmailAuthForm.vue'
export { default as ForgotPasswordForm } from './components/ForgotPasswordForm.vue'
